<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=yes, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Index</title>
</head>
<body>
<h1>Стр. Welcome. Добро пожаловать в "КупиПродай".</h1>
<div><a href="/products">Список объявлений</a></div>
<div><a href="/login">Форма авторизации</a></div>
<div><a href="/registration">Форма регистрации пользователя</a></div>
<div><a href="/hello">Hello</a></div>
</body>
</html>